# Generated by Django 5.0.1 on 2024-01-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_resource_course_resource_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=255),
        ),
    ]
