# Generated by Django 5.0.1 on 2024-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0008_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('student', 'Student')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
